# Generated by Django 5.2.4 on 2025-08-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appshop', '0002_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
